{
  "Select target plc: ": "Выберите целевое устройство: ",
  "New file": "Новый",
  "Open file": "Открыть...",
  "Save file": "Сохранить",
  "Save file as...": "Сохранить как...",
  "Run SoftPlc": "Запустить SoftPlc",
  "Suspend SoftPlc": "Приостановить SoftPlc",
  "Stop SoftPlc": "Остановить SoftPlc",
  "Copy": "Копировать",
  "Cut": "Вырезать",
  "Paste": "Вставить",
  "File": "Файл",
  "Edit": "Редактировать",
  "Select target": "Выберите устройство",
  "Library: ": "Библиотека: ",
  "Time": "Время",
  "Mode": "Режим",
  "Message": "Сообщение",
  "There are changes, do you want to save?": "Есть изменения, вы хотите сохранить?",
  "Yes": "Да",
  "No": "Нет",
  "Cancel": "Отмена",
  "Settings": "Настройки",
  "Unable to set parameter value: ": "Невозможно установить параметр: ",
  "The number is less than the minimum!\n": "Число меньше установленного минимума!\n",
  "The number is greater than the maximum!\n": "Число больше установленного максимума!\n",
  "The maximum and minimum parameters are incorrect\n": "Максимальный и минимальный параметры некоректны\n",
  "Parameter is not set!\n": "Параметр не установлен\n",
  "Error set parameter: ": "Ошибка установки параметра: ",
  "Error": "Ошибка",
  "Save": "Сохранить",
  "Parameters not set. ": "Параметры не установлены. ",
  "Server MBRTU" : "Сервер MBRTU",
  "on": "на",
  "Started" : "Запущен",
  "Stopped": "Остановлен",
}